export const Montserrat = {
  montserratBlack: require("./Montserrat-Black.ttf"),
  montserratBlackItalic: require("./Montserrat-BlackItalic.ttf"),
  montserratBold: require("./Montserrat-Bold.ttf"),
  montserratBoldItalic: require("./Montserrat-BoldItalic.ttf"),
  montserratExtraBold: require("./Montserrat-ExtraBold.ttf"),
  montserratExtraBoldItalic: require("./Montserrat-ExtraBoldItalic.ttf"),
  montserratExtraLight: require("./Montserrat-ExtraLight.ttf"),
  montserratExtraLightItalic: require("./Montserrat-ExtraLightItalic.ttf"),
  montserratItalic: require("./Montserrat-Italic.ttf"),
  montserratLight: require("./Montserrat-Light.ttf"),
  montserratLightItalic: require("./Montserrat-LightItalic.ttf"),
  montserratMedium: require("./Montserrat-Medium.ttf"),
  montserratMediumItalic: require("./Montserrat-MediumItalic.ttf"),
  montserratRegular: require("./Montserrat-Regular.ttf"),
  montserratSemiBold: require("./Montserrat-SemiBold.ttf"),
  montserratSemiBoldItalic: require("./Montserrat-SemiBoldItalic.ttf"),
  montserratThin: require("./Montserrat-Thin.ttf"),
  montserratThinItalic: require("./Montserrat-ThinItalic.ttf"),
};
